routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\QuestionController::class, 'index']);

Auth::routes();

// Route resource for Category
Route::resource('categories', App\Http\Controllers\CategoryController::class);

// Route resource for Question
Route::resource('questions', App\Http\Controllers\QuestionController::class);

Route::get('/user_question', [App\Http\Controllers\QuestionController::class, 'user_question']);

Route::post('/', [App\Http\Controllers\QuestionController::class, 'search']);

Route::post('/user_question', [App\Http\Controllers\QuestionController::class, 'search_user_question']);

// Route resource for Answer
Route::resource('answers', App\Http\Controllers\AnswerController::class);
Route::get('/answers/create/{id_question}', [App\Http\Controllers\AnswerController::class, 'create'])->name('answer.id.create');
Route::get('/user_answer', [App\Http\Controllers\AnswerController::class, 'user_answer'])->name('answered.by.user');

// Route for User Profile
Route::resource('users', App\Http\Controllers\UserController::class);

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $fillable = ['user_id', 'title', 'content', 'vote'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function question_category()
    {
        return $this->hasMany(QuestionCategory::class, 'question_id', 'id');
    }

    public function category()
    {
        return $this->belongsToMany(Category::class, 'question_categories');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use App\Models\Question;
use App\Models\Category;
use App\Models\QuestionCategory;
use Alert;

class QuestionController extends Controller
{
    public function index()
    {
        $questions = Question::all();
        
        return view('all_questions')->with([
            'questions' => $questions,
            'search' => ''
        ]);
    }

    public function search(Request $request)
    {
        $questions = Question::whereRaw("UPPER(title) LIKE '%". strtoupper($request['search'])."%'")->get(); 

        return view('all_questions')->with([
            'questions' => $questions,
            'search' => $request['search']
        ]);
    }

    public function create()
    {
        if (!Auth::check()) return redirect('/login');

        $categories = Category::all();
        
        return view('question.create_question', compact('categories'));
    }

    public function store(Request $request)
    {  
        $request->validate([
            'title' => 'required|max:45',
            'content' => 'required',
            'category' => 'required'
        ]);

        $question = Question::create([
            'user_id' => Auth::id(),
    		'title' => $request['title'],
            'content' => $request['content']
    	]);

        for ($i = 0; $i < sizeof($request['category']); $i++)
        {
            QuestionCategory::create([
                'category_id' => $request['category'][$i],
                'question_id' => $question->id
            ]);
        }

        return redirect()->route('questions.index')->with('success','Question successfully posted');
    }

    public function show($id)
    {
        $question = Question::find($id);

        return view('question.show_question', compact('question'));
    }

    public function edit($id)
    {
        $question = Question::find($id);

        $categories = Category::all();

        return view('question.edit_question', compact('question', 'categories'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required|max:45',
            'content' => 'required',
            'category' => 'required'
        ]);

        $question = Question::find($id)->update([
            'user_id' => Auth::id(),
    		'title' => $request['title'],
            'content' => $request['content']
    	]);

        $question_category = QuestionCategory::where('question_id', $id)->delete();

        for ($i = 0; $i < sizeof($request['category']); $i++)
        {
            QuestionCategory::create([
                'category_id' => $request['category'][$i],
                'question_id' => $id
            ]);
        }

        return redirect('/user_question')->with('success','Question updated successfully');
    }

    public function destroy($id)
    {
        $question = Question::find($id)->delete();

        return back()->with('Success', 'Question deleted successfully');
    }

    public function user_question()
    {
        $questions = Question::where('user_id', Auth::id())->orderBy('created_at')->get();

        return view('question.user_question')->with([
            'questions' => $questions,
            'search' => ''
        ]);
    }

    public function search_user_question(Request $request)
    {
        $questions = Question::whereRaw("user_id = " . Auth::id() . " AND UPPER(title) LIKE '%". strtoupper($request['search'])."%'")->orderBy('created_at')->get();

        return view('question.user_question')->with([
            'questions' => $questions,
            'search' => $request['search']
        ]);
    }
}

resources/views/question/create_question.blade.php
@extends('layouts.master')

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Create new questions</h6>
        </div>
        <div class="card-body">
            <form method="post" action="{{ route('questions.store') }}">
                @csrf
                <div class="form-group">
                    <label for="title">Question Title</label>
                    <input type="text" class="form-control" name="title" placeholder="Question Title">
                    @error('title')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="category">Question Category</label>
                    <select name="category[]" id="select-category" class="form-control" multiple="multiple">
                        @foreach ($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                        @endforeach
                    </select>
                    @error('category')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="content">Question Content</label>
                    <textarea name="content" class="form-control" id="input-content" cols="30" rows="10" placeholder="Question Content"></textarea>
                    @error('content')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <input type="submit" class="btn btn-primary" id="btn-submit" value="Input Question">
            </form>
        </div>
    </div>
    @include('sweetalert::alert')
@endsection

@push('script')
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        tinymce.init({
            selector: 'textarea#input-content', // Replace this CSS selector to match the placeholder element for TinyMCE
            plugins: 'powerpaste advcode table lists checklist',
            toolbar: 'undo redo | blocks| bold italic | bullist numlist checklist | code | table',
            elementpath: false
        });

        $('#btn-submit').click(function(event){
            var form =  $(this).closest("form");
            event.preventDefault();
            new swal({
                title: "Post Question",
                text: "Are you sure you want to post this question?",
                icon: "info",
                type: "info",
                showCancelButton: true,
                showConfirmButton: true
            }).then((willPost) => {
                if (willPost.isConfirmed) {
                    form.submit();
                }
            });
        });

        $('select').selectpicker('refresh');
    </script>
@endpush

@push('css')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
@endpush

resources/views/question/edit_question.blade.php
@extends('layouts.master')

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Create new questions</h6>
        </div>
        <div class="card-body">
            <form method="post" action="{{ route('questions.update', $question->id) }}">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="title">Question Title</label>
                    <input type="text" class="form-control" name="title" placeholder="Question Title" value="{{$question->title}}">
                    @error('title')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="category">Question Category</label>
                    <select name="category[]" id="select-category" class="form-control" multiple="multiple">
                        @foreach ($categories as $category)
                            @if (in_array($category->id, $question->question_category->pluck('category_id')->toArray()))
                                <option value="{{$category->id}}" selected>{{$category->name}}</option>
                            @else
                            <option value="{{$category->id}}">{{$category->name}}</option>
                            @endif
                        @endforeach
                    </select>
                    @error('category')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="content">Question Content</label>
                    <textarea name="content" class="form-control" id="input-content" cols="30" rows="10" placeholder="Question Content">{!!$question->content!!}</textarea>
                    @error('content')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <input type="submit" class="btn btn-primary" id="btn-submit" value="Edit Question">
            </form>
        </div>
    </div>
    @include('sweetalert::alert')
@endsection

@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        tinymce.init({
            selector: 'textarea#input-content', // Replace this CSS selector to match the placeholder element for TinyMCE
            plugins: 'powerpaste advcode table lists checklist',
            toolbar: 'undo redo | blocks| bold italic | bullist numlist checklist | code | table',
            elementpath: false
        });

        $('#btn-submit').click(function(event){
            var form =  $(this).closest("form");
            event.preventDefault();
            new swal({
                title: "Edit Question",
                text: "Are you sure you want to edit this question?",
                icon: "info",
                type: "info",
                showCancelButton: true,
                showConfirmButton: true
            }).then((willPost) => {
                if (willPost.isConfirmed) {
                    form.submit();
                }
            });
        });
    </script>
@endpush

resources/views/question/show_question.blade.php
@extends('layouts.master')

@section('content')
<h1>{{$question->title}}</h1>
<div class="card border-left-primary shadow mb-5">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Asked by {{ $question->name }}</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <p>#{{implode(' #', $question->category->pluck('name')->toArray())}}</p>
            </div>
        </div>
        <p class="card-text">{!! $question->content !!}</p>
    </div>
</div>

<h3>Jawaban</h3>
@forelse ($answers as $answer)
    <div class="card shadow border-left-info mb-3">
        <div class="card-header">
            <h6 class="m-0 font-weight-bold text-primary">Answer by {{$answer->user->name}}</h6>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    {!!$answer->content!!}
                </div>
            </div>
        </div>
    </div>
@empty 
    <p>Belum ada jawaban</p>
@endforelse

@endsection

resources/views/question/user_question.blade.php
@extends('layouts.master')

@section('search')
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" method="POST" action="/user_question">
        @csrf
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" name="search" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2" value="{{$search}}">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>
@endsection

@section('content')
    <h1>All of Your Question</h1>
    <div class="row">
        <div class="col-4">
            <a href="{{route('questions.create')}}" class="btn btn-primary">Ask another Question</a>
        </div>
    </div>

    @include('sweetalert::alert')
    
    @forelse ($questions as $question)
        <div class="row mt-4">
            <div class="col-12">
                <div class="card shadow">
                    <div class="card-header">
                        <a href="{{route('answers.show', $question->id)}}">{{$question->title}}</a>
                        {{-- Ask by {{$question->user->name}} --}}
                        <span class="float-right">
                            <a href="{{route('questions.edit', $question->id)}}"><i class="fas fa-edit ml-2"></i></a>
                            {{-- <a href="{{route('questions.destroy', $question->id)}}" data-confirm-delete="true"><i class="fas fa-trash"></i></a> --}}
                            <a href="" onclick="confirmDelete({{$question->id}})">
                                <i class="fas fa-trash ml-2"></i>
                            </a>
                            <form id="delete-question-{{ $question->id }}" action="{{ route('questions.destroy', $question->id) }}"
                                method="POST" style="display: none;">
                               @csrf
                               @method('DELETE')
                           </form>
                        </span>
                    </div>
                    <div class="card-body">
                        {{-- <div class="row">
                            <div class="col-12">
                                <a href="{{route('questions.show', $question->id)}}">{{$question->title}}</a>
                            </div>
                        </div> --}}
                        <div class="row">
                            <div class="col-12">
                                <p>#{{implode(' #', $question->category->pluck('name')->toArray())}}</p>
                            </div>
                        </div>
                        <p class="card-text">{!! $question->content !!}</p>
                    </div>
                </div>
            </div>
        </div>
    @empty
        <div class="row mt-4">
            <div class="col-12">
                You have not post any question yet
            </div>
        </div>
    @endforelse
@endsection

@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function confirmDelete($id)
        {
            event.preventDefault();
            new swal({
                title: "Delete Question",
                text: "Are you sure you want to delete this question?",
                icon: "info",
                type: "info",
                showCancelButton: true,
                showConfirmButton: true
            }).then((willDelete) => {
                    if (willDelete.isConfirmed) {
                        $(`#delete-question-${$id}`).submit();
                }
            });
        }
    </script>
@endpush