routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\QuestionController::class, 'index']);

Auth::routes();

// Route resource for Category
Route::resource('categories', App\Http\Controllers\CategoryController::class);

// Route resource for Question
Route::resource('questions', App\Http\Controllers\QuestionController::class);

Route::get('/user_question', [App\Http\Controllers\QuestionController::class, 'user_question']);

Route::post('/', [App\Http\Controllers\QuestionController::class, 'search']);

Route::post('/user_question', [App\Http\Controllers\QuestionController::class, 'search_user_question']);

// Route resource for Answer
Route::resource('answers', App\Http\Controllers\AnswerController::class);
Route::get('/answers/create/{id_question}', [App\Http\Controllers\AnswerController::class, 'create'])->name('answer.id.create');
Route::get('/user_answer', [App\Http\Controllers\AnswerController::class, 'user_answer'])->name('answered.by.user');

// Route for User Profile
Route::resource('users', App\Http\Controllers\UserController::class);

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $fillable = ['user_id', 'question_id', 'content', 'vote', 'is_valid'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    public function question()
    {
        return $this->belongsTo(Question::class, 'question_id');
    }
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Question;

class AnswerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id_question)
    {
        if (!Auth::check()) return redirect('/login');

        $question = Question::find($id_question);
        // join('users', 'questions.user_id', '=', 'users.id')
        //             ->get(['questions.*', 'users.name'])
        //             ->find($id_question);
        // dd($question);
        return view('answer.create_answer', compact('question'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request);
        $request->validate([
            'content' => 'required',
        ]);
        $question = Answer::create([
            'user_id' => Auth::id(),
            'question_id' => $request['question_id'], 
            'content' => $request['content']
    	]);
        return redirect()->route('questions.index')->with('success','Answer successfully posted');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function show($id_question)
    {
        //
        $question = Question::join('users', 'questions.user_id', '=', 'users.id')
                    ->where('questions.id',$id_question)
                    ->get(['questions.*', 'users.name']);
        $answers = Answer::join('users', 'answers.user_id', '=', 'users.id')
                    ->where('question_id',$id_question)
                    ->get(['answers.*', 'users.name']);
        // dd($question);
        return view('question.show_question')->with([
            'question' => $question[0],
            'answers' => $answers,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function edit($id_answer)
    {
        //
        $answer = Answer::find($id_answer);
        return view('answer.edit_answer', compact('answer'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_answer)
    {
        //
        $request->validate([
            'content' => 'required',
        ]);
        $answer = Answer::find($id_answer)->update([
            // 'user_id' => Auth::id(),
            'content' => $request['content']
        ]);
        return redirect()->route('answered.by.user')->with('success','Answer successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_answer)
    {
        //
        $answer = Answer::find($id_answer)->delete();
        return back()->with('Success', 'Answer deleted successfully');
    }

    public function user_answer()
    {
        $answers = Answer::where('user_id', Auth::id())->orderBy('created_at')->get();

        return view('answer.user_answer')->with([
            'answers' => $answers,
        ]);
    }
}

resources/views/answer/create_answer.blade.php
@extends('layouts.master')

@section('content')
    <h1>Jawab pertanyaan</h1>
    <div class="card border-left-primary shadow mb-3">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{ $question->title }}</h6>
        </div>
        <div class="card-body">
            <p class="card-text">{!! $question->content !!}</p>
        </div>
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Answer the question from {{ $question->user->name }}</h6>
        </div>
        <div class="card-body">
            <form method="post" action="{{ route('answers.store') }}">
                @csrf
                <div class="form-group">
                    <label for="content">Your Answer</label>
                    <textarea name="content" class="form-control" id="input-content" cols="30" rows="10" placeholder="Question Content"></textarea>
                    @error('content')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <input type="hidden" id="question_id" name="question_id" value="{{ $question->id }}">
                <input type="submit" class="btn btn-primary" id="btn-submit" value="Input Answer">
            </form>
        </div>
    </div>
    @include('sweetalert::alert')
@endsection

@push('script')
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        tinymce.init({
            selector: 'textarea#input-content', // Replace this CSS selector to match the placeholder element for TinyMCE
            plugins: 'powerpaste advcode table lists checklist',
            toolbar: 'undo redo | blocks| bold italic | bullist numlist checklist | code | table',
            elementpath: false
        });

        $('#btn-submit').click(function(event){
            var form =  $(this).closest("form");
            event.preventDefault();
            new swal({
                title: "Post Answer",
                text: "Are you sure you want to post this answer?",
                icon: "info",
                type: "info",
                showCancelButton: true,
                showConfirmButton: true
            }).then((willPost) => {
                if (willPost.isConfirmed) {
                    form.submit();
                }
            });
        });

        $('select').selectpicker('refresh');
    </script>
@endpush

@push('css')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
@endpush

resources/views/answer/edit_answer.blade.php
@extends('layouts.master')

@section('content')
    <h1>Edit Jawaban</h1>
    <div class="card border-left-primary shadow mb-3">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{ $answer->question->title }}</h6>
        </div>
        <div class="card-body">
            <p class="card-text">{!! $answer->question->content !!}</p>
        </div>
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit your answer for the question from {{ $answer->question->user->name }}</h6>
        </div>
        <div class="card-body">
            <form method="post" action="{{ route('answers.update', $answer->id) }}">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="content">Your Answer</label>
                    <textarea name="content" class="form-control" id="input-content" cols="30" rows="10" placeholder="Question Content">{!!$answer->content!!}</textarea>
                    @error('content')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <input type="submit" class="btn btn-primary" id="btn-submit" value="Edit Answer">
            </form>
        </div>
    </div>
    @include('sweetalert::alert')
@endsection
@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        tinymce.init({
            selector: 'textarea#input-content', // Replace this CSS selector to match the placeholder element for TinyMCE
            plugins: 'powerpaste advcode table lists checklist',
            toolbar: 'undo redo | blocks| bold italic | bullist numlist checklist | code | table',
            elementpath: false
        });

        $('#btn-submit').click(function(event){
            var form =  $(this).closest("form");
            event.preventDefault();
            new swal({
                title: "Edit Question",
                text: "Are you sure you want to edit this question?",
                icon: "info",
                type: "info",
                showCancelButton: true,
                showConfirmButton: true
            }).then((willPost) => {
                if (willPost.isConfirmed) {
                    form.submit();
                }
            });
        });
    </script>
@endpush

resources/views/answer/user_answer.blade.php
@extends('layouts.master')
@section('content')
    <h1>All of Your Answer</h1>
    <div class="row">
        <div class="col-4">
            <a href="/" class="btn btn-primary">Answer another Question</a>
        </div>
    </div>

    @include('sweetalert::alert')
    
    @forelse ($answers as $answer)
        <div class="row mt-4">
            <div class="col-12">
                <div class="card shadow">
                    <div class="card-header">
                        <a href="{{route('answers.show', $answer->question->id)}}">{{$answer->question->title}}</a>
                        {{-- Ask by {{$question->user->name}} --}}
                        <span class="float-right">
                            <a href="{{route('answers.edit', $answer->id)}}"><i class="fas fa-edit ml-2"></i></a>
                            {{-- <a href="{{route('questions.destroy', $question->id)}}" data-confirm-delete="true"><i class="fas fa-trash"></i></a> --}}
                            <a href="" onclick="confirmDelete({{$answer->id}})">
                                <i class="fas fa-trash ml-2"></i>
                            </a>
                            <form id="delete-answer-{{ $answer->id }}" action="{{ route('answers.destroy', $answer->id) }}"
                                method="POST" style="display: none;">
                               @csrf
                               @method('DELETE')
                           </form>
                        </span>
                    </div>
                    <div class="card-body">
                        {{-- <div class="row">
                            <div class="col-12">
                                <a href="{{route('questions.show', $question->id)}}">{{$question->title}}</a>
                            </div>
                        </div> --}}
                        <code>Your Answer:</code>
                        <div class="row">
                            <div class="col-12">
                                {!!$answer->content!!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @empty
        <div class="row mt-4">
            <div class="col-12">
                You have not post any answer yet
            </div>
        </div>
    @endforelse
@endsection

@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function confirmDelete($id)
        {
            event.preventDefault();
            new swal({
                title: "Delete Answer",
                text: "Are you sure you want to delete this answer?",
                icon: "info",
                type: "info",
                showCancelButton: true,
                showConfirmButton: true
            }).then((willDelete) => {
                    if (willDelete.isConfirmed) {
                        $(`#delete-answer-${$id}`).submit();
                }
            });
        }
    </script>
    @include('sweetalert::alert')
@endpush