routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\QuestionController::class, 'index']);

Auth::routes();

// Route resource for Category
Route::resource('categories', App\Http\Controllers\CategoryController::class);

// Route resource for Question
Route::resource('questions', App\Http\Controllers\QuestionController::class);

Route::get('/user_question', [App\Http\Controllers\QuestionController::class, 'user_question']);

Route::post('/', [App\Http\Controllers\QuestionController::class, 'search']);

Route::post('/user_question', [App\Http\Controllers\QuestionController::class, 'search_user_question']);

// Route resource for Answer
Route::resource('answers', App\Http\Controllers\AnswerController::class);
Route::get('/answers/create/{id_question}', [App\Http\Controllers\AnswerController::class, 'create'])->name('answer.id.create');
Route::get('/user_answer', [App\Http\Controllers\AnswerController::class, 'user_answer'])->name('answered.by.user');

// Route for User Profile
Route::resource('users', App\Http\Controllers\UserController::class);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    public function question_category()
    {
        return $this->hasMany(QuestionCategory::class, 'category_id', 'id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $category = Category::all();
        return view ('category.indexCategory',compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view ('category.createCategory');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
    		'name' => 'required|unique:categories,name',
    	]);
   
        Category::create([
    		'name' => $request->name,
    	]);
        return redirect()->route('categories.index')->with('success','Category created successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $category = Category::find($id);
        return view ('category.editCategory',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
    		'name' => 'required|unique:categories,name',
    	]);
           
        Category::find($id)->update([
    		'name' => $request->name,
    	]);
        return redirect()->route('categories.index')->with('success','Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // destroy data
        $category = Category::find($id);
        $category->delete();
        return redirect()->route('categories.index')->with('success','Category deleted successfully');
    }
}

resources/views/category/createCategory.blade.php
@extends('layouts.master')
@section('page_title', 'Create Category')

@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Create new categories</h6>
    </div>
    <div class="card-body">
        <form method="post" action="{{ route('categories.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">Category Name</label>
                <input type="text" class="form-control" name="name" placeholder="Category Name">
                @error('name')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <input type="submit" class="btn btn-primary" value="Input Category">
        </form>
    </div>
</div>
@endsection

resources/views/category/editCategory.blade.php
@extends('layouts.master')
@section('page_title', 'Edit Category')

@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Create new categories</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('categories.update', $category->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="name">Edit category name</label>
                <input type="text" class="form-control" name="name" value="{{$category->name}}">
            </div>
        
            <p>Apapun yang berubah akan tersimpan setelah disubmit dengan tombol dibawah ini</p>
            <input type="submit" class="btn btn-danger" value="Update Data Category">
        </form>
    </div>
</div>
@endsection

resources/views/category/indexCategory.blade.php
@extends('layouts.master')
@push('style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.css"/>
@endpush
@section('page_title', 'Category')

@section('content')
    <a href="{{ route('categories.create') }}" class="btn btn-primary my-2">Buat data baru</a>
    <div class="card shadow mb-4">
      <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
      </div>
      <div class="card-body">
          <div class="table-responsive">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nama</th>
                        <th>Detail</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($category as $cat)
                        <tr>
                            <td>{{ $cat->id }}</td>
                            <td>{{ $cat->name }}</td>
                            <td>
                                {{-- <!-- <a href="{{ route('categories.show', $c->id) }}" class="btn btn-primary">Detail</a> --> --}}
                                <a href="{{ route('categories.edit', $cat->id) }}" class="btn btn-success">Edit</a>
                                <form action="{{route('categories.destroy', $cat->id)}}" method="post">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
          </div>
      </div>
    </div>
@endsection

@push('script')
<script src="{{asset('sb_admin/vendor/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('sb_admin/vendor/datatables/dataTables.bootstrap4.js')}}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
@endpush