routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\QuestionController::class, 'index']);

Auth::routes();

// Route resource for Category
Route::resource('categories', App\Http\Controllers\CategoryController::class);

// Route resource for Question
Route::resource('questions', App\Http\Controllers\QuestionController::class);

Route::get('/user_question', [App\Http\Controllers\QuestionController::class, 'user_question']);

Route::post('/', [App\Http\Controllers\QuestionController::class, 'search']);

Route::post('/user_question', [App\Http\Controllers\QuestionController::class, 'search_user_question']);

// Route resource for Answer
Route::resource('answers', App\Http\Controllers\AnswerController::class);
Route::get('/answers/create/{id_question}', [App\Http\Controllers\AnswerController::class, 'create'])->name('answer.id.create');
Route::get('/user_answer', [App\Http\Controllers\AnswerController::class, 'user_answer'])->name('answered.by.user');

// Route for User Profile
Route::resource('users', App\Http\Controllers\UserController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'age', 'bio', 'address'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get all of the comments for the User
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function question()
    {
        return $this->hasMany(Question::class, 'user_id', 'id');
    }
    public function answer()
    {
        return $this->hasMany(Answer::class, 'user_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\User;
use Alert;

class UserController extends Controller
{
    public function index()
    {
        $user = User::find(Auth::id());

        return view('user.profile', compact('user'));
    }

    public function edit()
    {
        $user = User::find(Auth::id());

        return view('user.edit_profile', compact('user'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'age' => 'required|integer',
            'bio' => 'required',
            'address' => 'required|max:45',
        ]);

        User::find($id)->update([
            'age' => $request['age'],
            'bio' => $request['bio'],
            'address' => $request['address']
        ]);

        return redirect()->route('users.index')->with('success', 'User Profile updated successfully');
    }
}

resources/views/user/edit_profile.blade.php
@extends('layouts.master')

@section('content')
    <h1>Edit Profile</h1>
    <form action="{{route('users.update', $user->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div class="row mt-2">
            <div class="col-12">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" value="{{$user->name}}" disabled>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <label for="email">Email</label>
                <input type="text" name="email" class="form-control" value="{{$user->email}}" disabled>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <label for="age">Age</label>
                <input type="number" name="age" class="form-control" value="{{$user->age}}">
                @error('age')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <label for="bio">Bio</label>
                <textarea name="bio" cols="30" rows="10" class="form-control">{{$user->bio}}</textarea>
                @error('bio')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <label for="address">Address</label>
                <input type="text" name="address" class="form-control" value="{{$user->address}}" maxlength="45">
                @error('address')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12">
                <button id="btn-submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>
    @include('sweetalert::alert')
@endsection

@push('script')
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $('#btn-submit').click(function(event){
            var form =  $(this).closest("form");
            event.preventDefault();
            new swal({
                title: "Edit Profile",
                text: "Are you sure you want to edit your profile?",
                icon: "info",
                type: "info",
                showCancelButton: true,
                showConfirmButton: true
            }).then((willEdit) => {
                if (willEdit.isConfirmed) {
                    form.submit();
                }
            });
        });

    </script>
@endpush

resources/views/user/profile.blade.php
@extends('layouts.master')

@section('content')
    <h1>Profile</h1>
    <div class="row mt-2">
        <div class="col-2">
            Name <span class="float-right">:</span>
        </div>
        <div class="col-10">
            {{$user->name}}
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-2">
            Email <span class="float-right">:</span>
        </div>
        <div class="col-10">
            {{$user->email}}
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-2">
            Age <span class="float-right">:</span>
        </div>
        <div class="col-10">
            {{!$user->age ? '-' : $user->age}}
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-2">
            Bio <span class="float-right">:</span>
        </div>
        <div class="col-10">
            {{!$user->bio ? '-' : $user->bio}}
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-2">
            Address <span class="float-right">:</span>
        </div>
        <div class="col-10">
            {{!$user->address ? '-' : $user->address}}
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12">
            <a href="{{route('users.edit', Auth::id())}}" class="btn btn-primary">Update Profile</a>
        </div>
    </div>
    @include('sweetalert::alert')
@endsection